// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7P5lsM1llRHBGnpnGys9HntDBZHzffyk',
    appId: '1:126557220646:web:25e57abe9350d66a0d5be7',
    messagingSenderId: '126557220646',
    projectId: 'easycoupon-38a26',
    authDomain: 'easycoupon-38a26.firebaseapp.com',
    storageBucket: 'easycoupon-38a26.appspot.com',
    measurementId: 'G-XYML26SB64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4bCv4tFqknt3oG2mjijTERNEZtsEfXpA',
    appId: '1:126557220646:android:cf6b337e22cdfe6a0d5be7',
    messagingSenderId: '126557220646',
    projectId: 'easycoupon-38a26',
    storageBucket: 'easycoupon-38a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJcEIUl_8brujQcHyao89KlhBfyEmulyc',
    appId: '1:126557220646:ios:811e561fb10a29a20d5be7',
    messagingSenderId: '126557220646',
    projectId: 'easycoupon-38a26',
    storageBucket: 'easycoupon-38a26.appspot.com',
    iosBundleId: 'com.example.easyCoupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJcEIUl_8brujQcHyao89KlhBfyEmulyc',
    appId: '1:126557220646:ios:811e561fb10a29a20d5be7',
    messagingSenderId: '126557220646',
    projectId: 'easycoupon-38a26',
    storageBucket: 'easycoupon-38a26.appspot.com',
    iosBundleId: 'com.example.easyCoupon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7P5lsM1llRHBGnpnGys9HntDBZHzffyk',
    appId: '1:126557220646:web:68f424aa579f6eed0d5be7',
    messagingSenderId: '126557220646',
    projectId: 'easycoupon-38a26',
    authDomain: 'easycoupon-38a26.firebaseapp.com',
    storageBucket: 'easycoupon-38a26.appspot.com',
    measurementId: 'G-VFVFFHYPFW',
  );
}
