// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIgRNkXVzxQ21bRV-QDtykA_uzJ8mXBho',
    appId: '1:812573739976:web:21822ab17b3446d983cefd',
    messagingSenderId: '812573739976',
    projectId: 'easy-coupon-bfc60',
    authDomain: 'easy-coupon-bfc60.firebaseapp.com',
    storageBucket: 'easy-coupon-bfc60.appspot.com',
    measurementId: 'G-X81RHZYC7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-HlQlpdRQdJHK-AU3VxHjLS3Ewd-4OI',
    appId: '1:812573739976:android:fa2d140a908c179983cefd',
    messagingSenderId: '812573739976',
    projectId: 'easy-coupon-bfc60',
    storageBucket: 'easy-coupon-bfc60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJGAh2txqFUTH6HnEvGJy2SiqJDTheWvs',
    appId: '1:812573739976:ios:fb5832de5a1c3ede83cefd',
    messagingSenderId: '812573739976',
    projectId: 'easy-coupon-bfc60',
    storageBucket: 'easy-coupon-bfc60.appspot.com',
    iosBundleId: 'com.example.easyCoupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJGAh2txqFUTH6HnEvGJy2SiqJDTheWvs',
    appId: '1:812573739976:ios:fb5832de5a1c3ede83cefd',
    messagingSenderId: '812573739976',
    projectId: 'easy-coupon-bfc60',
    storageBucket: 'easy-coupon-bfc60.appspot.com',
    iosBundleId: 'com.example.easyCoupon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIgRNkXVzxQ21bRV-QDtykA_uzJ8mXBho',
    appId: '1:812573739976:web:0289f056c1138f9a83cefd',
    messagingSenderId: '812573739976',
    projectId: 'easy-coupon-bfc60',
    authDomain: 'easy-coupon-bfc60.firebaseapp.com',
    storageBucket: 'easy-coupon-bfc60.appspot.com',
    measurementId: 'G-RNXL1MQGL0',
  );

}